spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: KAKAO
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.7.116:8080/login/oauth2/code/kakao #https://port-0-backend-12fhqa2blnm78fgt.sel5.cloudtype.app/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  jwt:
    access-key: ${JWT_ACCESS_KEY}
    access-expire: ${JWT_ACCESS_EXPIRE}
  clova:
    name: ${CLOVA_NAME}
    client-id: ${CLOVA_CLIENT_ID}
    client-secret: ${CLOVA_CLIENT_SECRET}